py_test(
    name="test1",
    imports=["lxml"],
    srcs=[":srcs/test1/test1.py"],
    main=":srcs/test1/test1.py",
)
py_test(
    name="hellowworld",
    imports=["yattag"],
    srcs=[":srcs/helloworld/helloworld_test.py"],
    main=":srcs/helloworld/helloworld_test.py",
)

